services:
  openclaw-gateway:
    image: openclaw:hlasg-1.2
    environment:
      - GOG_KEYRING_BACKEND=${GOG_KEYRING_BACKEND}
      - GOG_KEYRING_PASSWORD=${GOG_KEYRING_PASSWORD}
      - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}
      - PATH=/home/linuxbrew/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile.hlasg
  openclaw-cli:
    image: openclaw:hlasg-1.1
    environment:
      - GOG_KEYRING_BACKEND=${GOG_KEYRING_BACKEND}
      - GOG_KEYRING_PASSWORD=${GOG_KEYRING_PASSWORD}
      - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}
      - PATH=/home/linuxbrew/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    env_file:
      - ./.env    
    build:
      context: .
      dockerfile: Dockerfile.hlasg
