services:
  openclaw-gateway:
    image: openclaw:hlasg-1.1
    environment:
      - GOG_KEYRING_BACKEND=${GOG_KEYRING_BACKEND}
      - GOG_KEYRING_PASSWORD=${GOG_KEYRING_PASSWORD}
#      - PATH=/home/linuxbrew/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}
    build:
      context: .
      dockerfile: Dockerfile.hlasg
   # volumes:
   #   - gog-config:/home/node/.config/gogcli
  openclaw-cli:
    image: openclaw:hlasg-1.1
    environment:
      - GOG_KEYRING_BACKEND=${GOG_KEYRING_BACKEND}
      - GOG_KEYRING_PASSWORD=${GOG_KEYRING_PASSWORD}
 #     - PATH=/home/linuxbrew/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - XDG_CONFIG_HOME=${XDG_CONFIG_HOME}
    #volumes:
    #  - gog-config:/home/node/.config/gogcli
    build:
      context: .
      dockerfile: Dockerfile.hlasg
